# Generated by Django 4.0.3 on 2022-04-04 17:48

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_superuser(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    _superuser = Profile.objects.create(username='hkrrio', email='moongloaming@gmail.com', password=make_password('111111'), is_superuser=True)
    _superuser.save()
    
def reverse_create_default_superuser(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for _superuser in Profile.objects.filter(username='hkrrio'):
        _superuser.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_superuser,
            reverse_create_default_superuser
        ),
    ]
    
