# Generated by Django 4.0.3 on 2022-03-03 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='FAX',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真號碼'),
        ),
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='department',
            name='addressEN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址(英文)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='addressJP',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址(日文)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話'),
        ),
        migrations.AlterField(
            model_name='package',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a8344212-3195-4f46-a341-d1a7e4b30961'), editable=False, primary_key=True, serialize=False, verbose_name='包裹唯一碼'),
        ),
    ]
