# Generated by Django 4.0.3 on 2022-04-04 18:19

from django.db import migrations
from django.db.models import Q

def create_default_country(apps, schema_editor):
    Country = apps.get_model('inventory', 'Country')
    _country = Country.objects.create(name='日本', code='JPN')
    _country.save()
    _country = Country.objects.create(name='台灣', code='TWN')
    _country.save()

def reverse_create_default_country(apps, schema_editor):
    Country = apps.get_model('inventory', 'Country')
    for _country in Country.objects.filter(Q(code='JPN') | Q(code='TWN')):
         _country.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_country, 
            reverse_create_default_country
        ),
    ]
