# Generated by Django 4.0.3 on 2022-04-04 19:24

from django.db import migrations
from django.db.models import Q

def create_default_department(apps, schema_editor):
    Department = apps.get_model('inventory', 'Department')
    _department = Department.objects.create(name='本社', phone='0476-85-5077', address='日本国〒287-0244 千葉県成田市川上２４５番地１６８０')
    _department.save()
    _department = Department.objects.create(name='成田倉庫', phone='0476−85−7989', address='日本国〒287-0241千葉県成田水の上９６２番地４４')
    _department.save()
    _department = Department.objects.create(name='上野営業所', phone='', address='日本国〒110-0014東京都台東区北上野２ー６ー１４')
    _department.save()
    
def reverse_create_default_department(apps, schema_editor):
    Department = apps.get_model('inventory', 'Department')
    for _department in Department.objects.filter(Q(name='本社') | Q(name='成田倉庫') | Q(name='上野営業所')):
         _department.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_create_default_company'),
    ]

    operations = [
        migrations.RunPython(
            create_default_department,
            create_default_department
        ),
    ]
