# Generated by Django 4.0.2 on 2022-03-02 18:24

import customers.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
                ('report', models.TextField(verbose_name='報告')),
            ],
            options={
                'verbose_name': '客戶拜訪報告',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('media_type', models.CharField(choices=[('Mobile', '手機'), ('Phone', '市話'), ('Line', 'Line'), ('WeChat', '微信'), ('FB', 'FaceBook'), ('Other', '其他')], default='Mobile', max_length=20, verbose_name='聯絡方式')),
                ('media_number', models.CharField(max_length=50, verbose_name='聯絡號碼')),
            ],
            options={
                'verbose_name': '顧客聯絡簿',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('nameJP', models.CharField(max_length=50, verbose_name='姓名(日)')),
                ('nameEN', models.CharField(max_length=50, verbose_name='姓名(英)')),
            ],
            options={
                'verbose_name': '顧客',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
            ],
            options={
                'verbose_name': '部門開發客戶',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
                ('number', models.CharField(max_length=20, verbose_name='貨運單號')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('name', models.CharField(max_length=20, verbose_name='收件人')),
                ('display', models.CharField(max_length=20, verbose_name='海關收件人')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡手機')),
                ('phone2', models.CharField(max_length=20, verbose_name='連絡電話')),
                ('description', models.TextField(verbose_name='備註')),
            ],
            options={
                'verbose_name': '物流清單',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('86061cd9-98d9-40dd-a71c-736b223e30a8'), editable=False, primary_key=True, serialize=False, verbose_name='訂單唯一碼')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='建檔時間')),
                ('order_number', models.CharField(default=customers.models.Get_Order_Number, max_length=12, unique=True, verbose_name='訂單編號')),
            ],
            options={
                'verbose_name': '訂單',
                'ordering': ['-createdon'],
            },
        ),
    ]
