# Generated by Django 4.0.3 on 2022-03-03 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ad37124d-1e7d-4d41-b76f-29a39b87c8b6'), editable=False, primary_key=True, serialize=False, verbose_name='訂單唯一碼'),
        ),
    ]
